title: Hello World
description: Just the Docs Exercise
theme: just-the-docs
color_scheme: dark
footer_content: "Very nice footer. Made by JS 2025"

url: https://JayStecki.github.io/jtdTestPage

aux_links:
  Template Repository: https://github.com/JayStecki/jtdTestPage
