title: Hello World
description: Just the Docs Exercise
theme: just-the-docs

url: https://JayStecki.github.io/Just-the-docs

aux_links:
  Template Repository: https://github.com/JayStecki/Just-the-docs
