title: Hello World
description: Just the Docs Exercise
theme: just-the-docs
color_scheme: dark
footer_content: "A nicer footer. Made by KS 2025"
logo: "images/DinoWifi.png"
favicon_ico: "/images/DinoWifi.ico"

url: https://JayStecki.github.io/jtdTestPage

aux_links:
  Template Repository: https://github.com/JayStecki/jtdTestPage
